export declare class HSCard {
    el: HTMLElement;
    imgHeaderImgContainer: HTMLImageElement;
    cardContent: any;
    colorTone: string;
    colorToneClass: string;
    cardId: string;
    cardSize: string;
    cardHeader: any;
    cardHeaderImg: HTMLElement;
    imgHeaderImgPlaceholder: string;
    overlay: any;
    imgElem: any;
    dataTarget?: string;
    dataToggle?: string;
    imgHeaderImg: string;
    imgPath: string;
    showHide: string;
    autoFooter: boolean;
    footerDiv: HTMLDivElement;
    basicFooter: any;
    clickTarget: string;
    cloneBaby: any;
    clonedContent: any;
    builderOne: any;
    builderTwo: any;
    builderThree: any;
    fnStatusCallBack: (status: boolean, fnName: string, errorMessage?: any) => any;
    validURL: (str: any) => any;
    componentWillLoad(): void;
    componenentWillRender(): void;
    render(): any;
}
