declare function stopAni(): void;
declare function ani(cf?: number): void;
declare function unify(e: any): any;
declare function lock(e: any): void;
declare function drag(e: any): void;
declare function move(e: any): void;
declare function size(): void;
declare const _C: Element;
declare const N: number;
declare const NF: 30;
declare const TFN: {
    'bounce-out': (k: any, a?: number, b?: number) => number;
};
declare let i: number;
declare let x0: any;
declare let locked: boolean;
declare let w: any;
declare let ini: any;
declare let fin: any;
declare let rID: any;
declare let anf: any;
declare let n: any;
