export default class HS3DRotate {
    rotatorContainer: HTMLDivElement;
    hs3dRotate: HTMLDivElement;
    cells: any;
    prevButton: HTMLButtonElement;
    nextButton: HTMLButtonElement;
    cellsRange: HTMLInputElement;
    orientationRadios: any;
    checkedRadio: HTMLInputElement;
    dataMethod: string;
    dataUrl: string;
    dataHeaders: string;
    cellSize: any;
    cellCount: any;
    selectedIndex: any;
    cellWidth: any;
    cellHeight: any;
    cellsRange: any;
    isHorizontal: boolean;
    rotateFn: string;
    radius: any;
    theta: any;
    orientationFlag: boolean;
    rotateEventsFlag: boolean;
    hs3dRotatorEvents: any;
    constructor(dataMethod1?: string, dataURL1?: string, dataHeaders1?: string);
    Get3dRotatorData(): any;
    init3dRotator: any;
    rotate3dRotator(): any;
    update3DRotator(): any;
    HS3dRotateEvents(): any;
}
